#!/usr/bin/env python3
"""sourcemapper: extract original source files from JavaScript sourcemaps.

A Python 3 rewrite of github.com/denandz/sourcemapper. Parses a sourcemap,
as generated by webpack or similar, and writes out the original source
files, recreating the source tree based on the paths in the sourcemap.

Uses only the Python standard library (Python 3.8+).
"""

import argparse
import base64
import binascii
import json
import logging
import os
import re
import ssl
import sys
import urllib.error
import urllib.parse
import urllib.request

log = logging.getLogger("sourcemapper")

# Matches sourceMappingURL comments in a JS body. A JS file can contain
# multiple of these, but only the last one is valid:
# https://sourcemaps.info/spec.html#h.lmz475t4mvbx
SOURCE_MAPPING_URL_RE = re.compile(rb"//[@#] sourceMappingURL=(.*)")

# Characters illegal in Windows paths.
WINDOWS_ILLEGAL_RE = re.compile(r'[?%*|:"<>]')


class SourceMapError(Exception):
    """Raised when a sourcemap cannot be retrieved or parsed."""


class SourceMap:
    """A sourcemap. We only really care about the sources and
    sourcesContent arrays."""

    __slots__ = ("version", "sources", "sources_content")

    def __init__(self, version=0, sources=None, sources_content=None):
        self.version = version
        self.sources = sources or []
        self.sources_content = sources_content or []


def build_opener(insecure_tls, proxy_url):
    """Build a urllib opener honoring the TLS and proxy options."""
    handlers = []
    if insecure_tls:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        handlers.append(urllib.request.HTTPSHandler(context=ctx))
    if proxy_url:
        handlers.append(
            urllib.request.ProxyHandler({"http": proxy_url, "https": proxy_url})
        )
    return urllib.request.build_opener(*handlers)


def parse_headers(headers):
    """Parse 'Name: value' strings, similar to curl's -H."""
    parsed = {}
    for header in headers:
        name, sep, value = header.partition(":")
        if not sep or not name.strip():
            raise SourceMapError(
                f"invalid header {header!r}, expected 'Name: value'"
            )
        parsed[name.strip()] = value.strip()
    return parsed


def http_get(url, headers, opener):
    """GET url and return (status, response headers, body).

    Non-2xx responses are returned instead of raising so callers can
    inspect the body, like the Go version does.
    """
    req = urllib.request.Request(url, headers=headers)
    try:
        with opener.open(req) as res:
            return res.status, res.headers, res.read()
    except urllib.error.HTTPError as e:
        return e.code, e.headers, e.read()


def get_source_map(source, headers, insecure_tls, proxy_url, remote_source):
    """Retrieve a sourcemap from a URL, data URI, or local file.

    If remote_source is true, only http/https/data schemes are allowed.
    Local file access is blocked to prevent arbitrary file reads from
    attacker-controlled sourceMappingURL values.
    """
    log.info("[+] Retrieving Sourcemap from %.1024s...", source)

    parsed = urllib.parse.urlparse(source)

    if parsed.scheme in ("http", "https"):
        # If it's a URL, get it.
        if headers:
            header_string = "\r\n".join(headers) + "\r\n\r\n"
            log.info("[+] Setting the following headers: \n%s", header_string)
        hdrs = parse_headers(headers)
        opener = build_opener(insecure_tls, proxy_url)
        try:
            status, _res_headers, body = http_get(parsed.geturl(), hdrs, opener)
        except urllib.error.URLError as e:
            raise SourceMapError(f"request failed: {e}") from e

        if status != 200 and len(body) > 0:
            log.warning(
                "[!] WARNING - non-200 status code: %d - Confirm this URL "
                "contains valid source map manually!", status
            )
            log.warning(
                "[!] WARNING - sourceMap URL request return != 200 - "
                "however, body length > 0 so continuing... "
            )
    elif parsed.scheme == "data":
        chunks = parsed.path.split(",")
        if len(chunks) < 2:
            raise SourceMapError(
                "[!] Could not parse data URI - expected at least 2 chunks "
                f"but got {len(chunks)}"
            )
        try:
            b64 = chunks[1] + "=" * (-len(chunks[1]) % 4)
            body = base64.b64decode(b64, validate=True)
        except (binascii.Error, ValueError) as e:
            raise SourceMapError(f"[!] Error base64 decoding: {e}") from e
    else:
        if remote_source:
            raise SourceMapError(
                f"[!] Refusing to read local file from remote "
                f"sourceMappingURL: {source}"
            )
        # If it's a file, read it.
        try:
            with open(source, "rb") as f:
                body = f.read()
        except OSError as e:
            raise SourceMapError(str(e)) from e

    # Unmarshall the body into the struct.
    log.info("[+] Read %d bytes, parsing JSON.", len(body))
    try:
        data = json.loads(body)
    except (ValueError, UnicodeDecodeError):
        log.warning(
            "[!] Error parsing JSON - confirm %s is a valid JS sourcemap",
            source,
        )
        raise SourceMapError(f"invalid sourcemap JSON: {source}") from None

    if not isinstance(data, dict):
        raise SourceMapError(f"invalid sourcemap JSON: {source}")

    return SourceMap(
        version=data.get("version") or 0,
        sources=data.get("sources"),
        sources_content=data.get("sourcesContent"),
    )


def get_source_map_from_js(jsurl, headers, insecure_tls, proxy_url):
    """Query a JavaScript URL, parse its headers and content, and look
    for sourcemaps, following the rules outlined in
    https://tc39.es/source-map-spec/#linking-generated-code
    """
    log.info("[+] Retrieving JavaScript from URL: %s.", jsurl)

    parsed = urllib.parse.urlparse(jsurl)
    if parsed.scheme not in ("http", "https"):
        raise SourceMapError(f"unsupported URL: {jsurl}")

    if headers:
        header_string = "\r\n".join(headers) + "\r\n\r\n"
        log.info("[+] Setting the following headers: \n%s", header_string)
    hdrs = parse_headers(headers)
    opener = build_opener(insecure_tls, proxy_url)

    try:
        status, res_headers, body = http_get(parsed.geturl(), hdrs, opener)
    except urllib.error.URLError as e:
        raise SourceMapError(f"request failed: {e}") from e

    if status != 200:
        raise SourceMapError(f"[!] non-200 status code: {status}")

    # check for SourceMap and X-SourceMap (deprecated) headers
    source_map_ref = res_headers.get("SourceMap") or res_headers.get("X-SourceMap")

    if source_map_ref:
        log.info(
            "[.] Found SourceMap URI in response headers: %.1024s...",
            source_map_ref,
        )
    else:
        # parse the javascript
        matches = SOURCE_MAPPING_URL_RE.findall(body)
        if matches:
            # only the sourcemap at the end of the file should be valid
            source_map_ref = matches[-1].strip().decode("utf-8", "replace")
            log.info(
                "[.] Found SourceMap in JavaScript body: %.1024s...",
                source_map_ref,
            )

    # this introduces a forced request bug if the JS file we're parsing is
    # malicious and forces us to make a request out to something dodgy - take care
    if source_map_ref:
        # handle absolute/relative rules
        source_map_url = urllib.parse.urljoin(jsurl, source_map_ref)
        return get_source_map(
            source_map_url, headers, insecure_tls, proxy_url, remote_source=True
        )

    raise SourceMapError("[!] No sourcemap URL found")


def write_file(path, content):
    """Write content to the file at path."""
    path = os.path.normpath(path)

    parent = os.path.dirname(path)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent, mode=0o700, exist_ok=True)

    data = (content or "").encode("utf-8")
    log.info("[+] Writing %d bytes to %s.", len(data), path)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(data)


def clean_windows(path):
    """Replace the illegal characters from a path."""
    return WINDOWS_ILLEGAL_RE.sub("", path)


def process_source_map(sm, outdir):
    """Extract the source files from a parsed sourcemap into outdir."""
    log.info(
        "[+] Retrieved Sourcemap with version %d, containing %d entries.",
        sm.version,
        len(sm.sources),
    )

    if len(sm.sources) == 0:
        raise SourceMapError("no sources found")

    if len(sm.sources_content) == 0:
        raise SourceMapError("no source content found")

    if sm.version != 3:
        log.warning("[!] Sourcemap is not version 3. This is untested!")

    if not os.path.isdir(outdir):
        os.makedirs(outdir, mode=0o700, exist_ok=True)

    for i, source_path in enumerate(sm.sources):
        # Prepending "/" and normalizing collapses any ".." so the result
        # is always rooted and cannot escape outdir.
        source_path = "/" + (source_path or "")
        # If on windows, clean the sourcepath.
        if sys.platform == "win32":
            source_path = clean_windows(source_path)

        # Strip the leading "/" so os.path.join keeps everything inside
        # outdir instead of replacing it.
        script_path = os.path.join(outdir, os.path.normpath(source_path).lstrip("/"))
        script_data = sm.sources_content[i] if i < len(sm.sources_content) else None

        try:
            write_file(script_path, script_data)
        except OSError as e:
            log.warning("Error writing %s file: %s", script_path, e)


def process_directory(args):
    """Walk args.dir recursively and process all .map files found."""
    map_files = []
    for root, _dirs, files in os.walk(args.dir):
        for name in files:
            if name.lower().endswith(".map"):
                map_files.append(os.path.join(root, name))

    map_files.sort()
    if not map_files:
        raise SourceMapError(f"No .map files found in {args.dir}")
    log.info("[+] Found %d .map files in %s", len(map_files), args.dir)

    for map_file in map_files:
        log.info("[+] Processing: %s", map_file)
        try:
            sm = get_source_map(
                map_file, args.headers, args.insecure, args.proxy,
                remote_source=False,
            )
            process_source_map(sm, args.output)
        except SourceMapError as e:
            log.warning("[!] Error processing %s: %s, skipping.", map_file, e)


def main():
    ap = argparse.ArgumentParser(
        prog="sourcemapper",
        description="Parse a sourcemap and extract the original source files.",
    )
    ap.add_argument(
        "--output", required=True, help="Source file output directory - REQUIRED"
    )
    ap.add_argument("--url", default="", help="URL or path to the Sourcemap file")
    ap.add_argument("--jsurl", default="", help="URL to JavaScript file")
    ap.add_argument(
        "--dir", default="", help="Directory of .map files to process recursively"
    )
    ap.add_argument("--proxy", default="", help="Proxy URL")
    ap.add_argument(
        "--insecure", action="store_true", help="Ignore invalid TLS certificates"
    )
    ap.add_argument(
        "--header",
        dest="headers",
        action="append",
        default=[],
        help="A header to send with the request, similar to curl's -H. "
        'Can be set multiple times, EG: "sourcemapper --header '
        '"Cookie: session=bar" --header "Authorization: blerp""',
    )
    args = ap.parse_args()

    # Ensure only one input mode is specified
    input_modes = [m for m in (args.url, args.jsurl, args.dir) if m]
    if len(input_modes) > 1:
        ap.error("Only one of --url, --jsurl, or --dir can be specified")

    try:
        if args.dir:
            # Walk the directory and process all .map files
            process_directory(args)
        elif args.url:
            sm = get_source_map(
                args.url, args.headers, args.insecure, args.proxy,
                remote_source=False,
            )
            process_source_map(sm, args.output)
        elif args.jsurl:
            sm = get_source_map_from_js(
                args.jsurl, args.headers, args.insecure, args.proxy
            )
            process_source_map(sm, args.output)
        else:
            ap.error("one of --url, --jsurl, or --dir is required")
    except SourceMapError as e:
        log.error("%s", e)
        sys.exit(1)

    log.info("[+] Done")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(message)s",
        datefmt="%Y/%m/%d %H:%M:%S",
    )
    main()
